# Deploying quarkus app as container aware application:
FROM registry.access.redhat.com/ubi8/openjdk-11:1.17-1.1693366250
COPY lib/my-app-1.0-SNAPSHOT.jar /deployments/my-app-1.0-SNAPSHOT.jar
CMD ["/opt/jboss/container/java/run/run-java.sh"]
